In [1]:
import pandas as pd
import numpy as np

In [153]:
ico_dates = pd.read_parquet("../OLHC_Completo.parquet.gzip")
df = pd.read_csv("../raw_data/df_coinID_index_as_columns.csv")

In [3]:
ico_dates

                       01coin                                \
                         Open      High       Low     Close
Date
2013-04-29 21:00:00       NaN       NaN       NaN       NaN
2013-05-02 21:00:00       NaN       NaN       NaN       NaN
2013-05-06 21:00:00       NaN       NaN       NaN       NaN
2013-05-10 21:00:00       NaN       NaN       NaN       NaN
2013-05-14 21:00:00       NaN       NaN       NaN       NaN
...                       ...       ...       ...       ...
2022-03-30 21:00:00  0.000468  0.000817  0.000468  0.000817
2022-04-02 21:00:00  0.000706  0.000706  0.000463  0.000466
2022-04-06 21:00:00  0.000467  0.000467  0.000436  0.000436
2022-04-10 21:00:00  0.000611  0.000611  0.000424  0.000424
2022-04-14 21:00:00  0.000420  0.000435  0.000359  0.000359

                    0-5x-long-algorand-token                                \
                                        Open      High       Low     Close
Date
2013-04-29 21:00:00                      NaN       NaN       NaN       NaN
2013-05-02 21:00:00                      NaN       NaN       NaN       NaN
2013-05-06 21:00:00                      NaN       NaN       NaN       NaN
2013-05-10 21:00:00                      NaN       NaN       NaN       NaN
2013-05-14 21:00:00                      NaN       NaN       NaN       NaN
...                                      ...       ...       ...       ...
2022-03-30 21:00:00                 15935.14  16211.44  15935.14  16211.44
2022-04-02 21:00:00                      NaN       NaN       NaN       NaN
2022-04-06 21:00:00                 14667.03  14667.03  14667.03  14667.03
2022-04-10 21:00:00                 14737.16  14737.16  14737.16  14737.16
2022-04-14 21:00:00                      NaN       NaN       NaN       NaN

                    0-5x-long-altcoin-index-token            ...  \
                                             Open      High  ...
Date                                                         ...
2013-04-29 21:00:00                           NaN       NaN  ...
2013-05-02 21:00:00                           NaN       NaN  ...
2013-05-06 21:00:00                           NaN       NaN  ...
2013-05-10 21:00:00                           NaN       NaN  ...
2013-05-14 21:00:00                           NaN       NaN  ...
...                                           ...       ...  ...
2022-03-30 21:00:00                      20398.08  20740.75  ...
2022-04-02 21:00:00                           NaN       NaN  ...
2022-04-06 21:00:00                           NaN       NaN  ...
2022-04-10 21:00:00                      20077.42  20077.42  ...
2022-04-14 21:00:00                           NaN       NaN  ...

                    zytara-dollar                 zyx                      \
                              Low     Close      Open      High       Low
Date
2013-04-29 21:00:00           NaN       NaN       NaN       NaN       NaN
2013-05-02 21:00:00           NaN       NaN       NaN       NaN       NaN
2013-05-06 21:00:00           NaN       NaN       NaN       NaN       NaN
2013-05-10 21:00:00           NaN       NaN       NaN       NaN       NaN
2013-05-14 21:00:00           NaN       NaN       NaN       NaN       NaN
...                           ...       ...       ...       ...       ...
2022-03-30 21:00:00      0.924853  0.987232  0.059673  0.059673  0.056143
2022-04-02 21:00:00      0.949777  0.990075  0.053293  0.053293  0.052032
2022-04-06 21:00:00      0.911270  0.911270  0.053346  0.053346  0.045867
2022-04-10 21:00:00      0.928492  1.030000  0.046599  0.049525  0.046599
2022-04-14 21:00:00      0.901227  1.090000  0.046212  0.049202  0.046071

                              zzz-finance-v2
                        Close           Open  High   Low Close
Date
2013-04-29 21:00:00       NaN            NaN   NaN   NaN   NaN
2013-05-02 21:00:00       NaN            NaN   NaN   NaN   NaN
2013-05-06 21:00:00       NaN            NaN   NaN   NaN   NaN
2013-05-10 21:00:00       NaN            NaN   NaN   NaN   NaN
2013-05-14 21:00:00       NaN            NaN   NaN   NaN   NaN
...                       ...            ...   ...   ...   ...
2022-03-30 21:00:00  0.056143            NaN   NaN   NaN   NaN
2022-04-02 21:00:00  0.052663           1.40  1.42  1.40  1.42
2022-04-06 21:00:00  0.045867           1.42  1.42  1.42  1.42
2022-04-10 21:00:00  0.049525            NaN   NaN   NaN   NaN
2022-04-14 21:00:00  0.046071            NaN   NaN   NaN   NaN

[861 rows x 52964 columns]

In [4]:
first_date = ico_dates['01coin'].dropna().index[0]

In [5]:
ico_dates['01coin'].loc[first_date:]

                         Open      High       Low     Close
Date
2018-09-14 21:00:00  0.009788  0.009788  0.009788  0.009788
2018-09-18 21:00:00  0.009883  0.012145  0.007965  0.011866
2018-09-22 21:00:00  0.011457  0.012510  0.009856  0.012510
2018-09-26 21:00:00  0.008730  0.010058  0.008105  0.008105
2018-09-29 21:00:00  0.009297  0.009297  0.007109  0.007109
...                       ...       ...       ...       ...
2022-03-30 21:00:00  0.000468  0.000817  0.000468  0.000817
2022-04-02 21:00:00  0.000706  0.000706  0.000463  0.000466
2022-04-06 21:00:00  0.000467  0.000467  0.000436  0.000436
2022-04-10 21:00:00  0.000611  0.000611  0.000424  0.000424
2022-04-14 21:00:00  0.000420  0.000435  0.000359  0.000359

[345 rows x 4 columns]

In [6]:
def first_date_onwards(dataset):
    coin_list = []
    for coin in dataset:
        first_date = dataset[f'{coin}'].dropna().index[0]
        dataset[f'{coin}'].loc[first_date]

In [7]:
a = ico_dates['0-5x-long-algorand-token'].dropna().index[0]
b = ico_dates['0-5x-long-algorand-token']['High'].dropna()[0]

In [8]:
a

Timestamp('2020-08-18 21:00:00')

In [9]:
b

11007.43

In [641]:
def get_dates():
    df = pd.read_csv("../raw_data/df_coinID_index_as_columns.csv")
    ico_dates = pd.read_parquet("../OLHC_Completo.parquet.gzip")
    coins_list = df.columns[1:].to_list()
    dates_dict = {}
    for coin in coins_list:
        try:
            first_date = ico_dates[f'{coin}'].dropna().index[0]
            data = ico_dates[f'{coin}'].loc[first_date:]
            dates_dict[f'{coin}'] = [data['Open'][0:100].fillna(method='ffill'), data['Close'][0:100].fillna(method='ffill')]
        except:
            pass
    df_final = pd.DataFrame.from_dict(dates_dict)
    return df_final.transpose()

In [656]:
%%time
coins_return_dict = {}
coins_list = []
df_dates_dict = df_dates[1].to_dict()
for coin in df_dates.index:
    coins_return_dict[coin] = {}
    try:
        coins_return_dict[coin]['launch_date'] = df_dates.loc[coin][1].index[0]
    except:
        coins_return_dict[coin]['launch_date'] = np.nan

    try:
        coins_return_dict[coin]['launch_price'] = df_dates[0][coin][0]
    except:
        coins_return_dict[coin]['launch_price'] = np.nan

    try:
        coins_return_dict[coin]['0days_price'] = df_dates_dict[coin][0]
    except:
        coins_return_dict[coin]['0days_price'] = np.nan

    try:
        coins_return_dict[coin]['4days_price'] = df_dates_dict[coin][1]
    except:
        coins_return_dict[coin]['4days_price'] = np.nan

    try:
        coins_return_dict[coin]['16days_price'] = df_dates_dict[coin][4]
    except:
        coins_return_dict[coin]['16days_price'] = np.nan

    try:
        coins_return_dict[coin]['28days_price'] = df_dates_dict[coin][8]
    except:
        coins_return_dict[coin]['28days_price'] = np.nan

    try:
        coins_return_dict[coin]['90days_price'] = df_dates_dict[coin][24]
    except:
        coins_return_dict[coin]['90days_price'] = np.nan

    try:
        coins_return_dict[coin]['180days_price'] = df_dates_dict[coin][48]
    except:
        coins_return_dict[coin]['180days_price'] = np.nan

    try:
        coins_return_dict[coin]['360days_price'] = df_dates_dict[coin][96]
    except:
        coins_return_dict[coin]['360days_price'] = np.nan

CPU times: user 909 ms, sys: 73.3 ms, total: 982 ms
Wall time: 1.04 s

In [644]:
df_dates = get_dates()

In [667]:
y_values = pd.DataFrame(coins_return_dict).T
y_values

,launch_date,launch_price,0days_price,4days_price,16days_price,28days_price,90days_price,180days_price,360days_price
01coin,2018-09-14 21:00:00,0.009788,0.009788,0.011866,0.007109,0.012722,0.006281,0.003229,0.00233
0-5x-long-algorand-token,2020-08-18 21:00:00,11007.43,11007.43,11086.45,11086.45,8892.7,7685.17,18153.99,15532.0
0-5x-long-altcoin-index-token,2020-10-22 21:00:00,7786.4,7786.4,7786.4,7764.67,7764.67,11937.12,21094.5,24044.81
0-5x-long-ascendex-token-token,2020-11-06 21:00:00,6605.01,6709.19,6775.99,6775.99,6775.99,6775.99,6775.99,6775.99
0-5x-long-bitcoin-cash-token,2020-08-06 21:00:00,7240.23,7240.23,7106.51,7048.08,6530.07,6460.55,8518.12,10055.18
...,...,...,...,...,...,...,...,...,...
thekey,2018-02-14 22:00:00,0.039353,0.039353,0.033518,0.02588,0.013316,0.021772,0.003772,0.002066
mooncake,2021-08-14 21:00:00,0.100341,0.102276,0.098183,0.140111,0.103399,0.021681,0.007072,NaN
wolf-game-wool,2021-11-22 21:00:00,0.176737,0.176737,0.120617,0.062816,0.057113,0.126638,NaN,NaN
misty-inu,2021-10-22 21:00:00,0.001384,0.001602,0.002878,0.000508,0.000126,0.000074,NaN,NaN
mintstarter,2022-03-18 21:00:00,0.009659,0.009659,0.006735,0.005172,NaN,NaN,NaN,NaN

In [668]:
y_values['0days_price'] = y_values['0days_price']/y_values['launch_price']-1
y_values['4days_price'] = y_values['4days_price']/y_values['launch_price']-1
y_values['16days_price'] = y_values['16days_price']/y_values['launch_price']-1
y_values['28days_price'] = y_values['28days_price']/y_values['launch_price']-1
y_values['90days_price'] = y_values['90days_price']/y_values['launch_price']-1
y_values['180days_price'] = y_values['180days_price']/y_values['launch_price']-1
y_values['360days_price'] = y_values['360days_price']/y_values['launch_price']-1
y_values

,launch_date,launch_price,0days_price,4days_price,16days_price,28days_price,90days_price,180days_price,360days_price
01coin,2018-09-14 21:00:00,0.009788,0.0,0.212301,-0.273702,0.299755,-0.358296,-0.670106,-0.761953
0-5x-long-algorand-token,2020-08-18 21:00:00,11007.43,0.0,0.007179,0.007179,-0.192118,-0.30182,0.649249,0.411047
0-5x-long-altcoin-index-token,2020-10-22 21:00:00,7786.4,0.0,0.0,-0.002791,-0.002791,0.533073,1.709147,2.088052
0-5x-long-ascendex-token-token,2020-11-06 21:00:00,6605.01,0.015773,0.025886,0.025886,0.025886,0.025886,0.025886,0.025886
0-5x-long-bitcoin-cash-token,2020-08-06 21:00:00,7240.23,0.0,-0.018469,-0.026539,-0.098085,-0.107687,0.176499,0.388793
...,...,...,...,...,...,...,...,...,...
thekey,2018-02-14 22:00:00,0.039353,0.0,-0.148273,-0.342363,-0.661627,-0.446751,-0.90415,-0.947501
mooncake,2021-08-14 21:00:00,0.100341,0.019284,-0.021507,0.396348,0.030476,-0.783927,-0.92952,NaN
wolf-game-wool,2021-11-22 21:00:00,0.176737,0.0,-0.317534,-0.644579,-0.676848,-0.283466,NaN,NaN
misty-inu,2021-10-22 21:00:00,0.001384,0.157514,1.07948,-0.632948,-0.90896,-0.946532,NaN,NaN
mintstarter,2022-03-18 21:00:00,0.009659,0.0,-0.302723,-0.464541,NaN,NaN,NaN,NaN

In [673]:
y_values

,launch_date,launch_price,0days_price,4days_price,16days_price,28days_price,90days_price,180days_price,360days_price
01coin,2018-09-14 21:00:00,0.009788,0.0,0.212301,-0.273702,0.299755,-0.358296,-0.670106,-0.761953
0-5x-long-algorand-token,2020-08-18 21:00:00,11007.43,0.0,0.007179,0.007179,-0.192118,-0.30182,0.649249,0.411047
0-5x-long-altcoin-index-token,2020-10-22 21:00:00,7786.4,0.0,0.0,-0.002791,-0.002791,0.533073,1.709147,2.088052
0-5x-long-ascendex-token-token,2020-11-06 21:00:00,6605.01,0.015773,0.025886,0.025886,0.025886,0.025886,0.025886,0.025886
0-5x-long-bitcoin-cash-token,2020-08-06 21:00:00,7240.23,0.0,-0.018469,-0.026539,-0.098085,-0.107687,0.176499,0.388793
...,...,...,...,...,...,...,...,...,...
thekey,2018-02-14 22:00:00,0.039353,0.0,-0.148273,-0.342363,-0.661627,-0.446751,-0.90415,-0.947501
mooncake,2021-08-14 21:00:00,0.100341,0.019284,-0.021507,0.396348,0.030476,-0.783927,-0.92952,NaN
wolf-game-wool,2021-11-22 21:00:00,0.176737,0.0,-0.317534,-0.644579,-0.676848,-0.283466,NaN,NaN
misty-inu,2021-10-22 21:00:00,0.001384,0.157514,1.07948,-0.632948,-0.90896,-0.946532,NaN,NaN
mintstarter,2022-03-18 21:00:00,0.009659,0.0,-0.302723,-0.464541,NaN,NaN,NaN,NaN

In [674]:
y_values.to_csv('../y_values.csv')

In [571]:
coins_return_dict = {}
coins_list = []
coin1 = coin2 = coin3 = coin4 = coin5 = 0

for coin in df_dates.index:
    dates_len = len(df_dates[1][coin].index)
    df_dates_closed = df_dates[1][coin]
    if dates_len == 1:
        coin1 = coin1 + 1
        coins_return_dict = {'Coin' : coin, 
                            'launch_date' : df_dates.loc[coin][1].index[0], 
                            'launch_price' : df_dates[0][coin][0],
                            '0days_price' :df_dates[1][coin][0]
                            }
        coins_list.append(coins_return_dict)
    elif dates_len < 5:
        coin2 = coin2 + 1
        coins_return_dict = {'Coin' : coin, 
                            'launch_date' : df_dates.loc[coin][1].index[0], 
                            'launch_price' : df_dates[0][coin][0],
                            '0days_price' :df_dates[1][coin][0],
                            '4days_price' :df_dates[1][coin][1]
                            }
        coins_list.append(coins_return_dict)
    elif dates_len >= 5 & dates_len <= 9:
        coin3 = coin3 + 1
        coins_return_dict = {'Coin' : coin, 
                            'launch_date' : df_dates.loc[coin][1].index[0], 
                            'launch_price' : df_dates[0][coin][0],
                            '0days_price' :df_dates[1][coin][0],
                            '4days_price' :df_dates[1][coin][1],
                            '14days_price' :df_dates[1][coin][4]
                            }
        coins_list.append(coins_return_dict)
    elif dates_len >= 9 & dates_len <= 17:
        coin4 = coin4 + 1
        coins_return_dict = {'Coin' : coin, 
                            'launch_date' : df_dates.loc[coin][1].index[0], 
                            'launch_price' : df_dates[0][coin][0],
                            '0days_price' :df_dates[1][coin][0],
                            '4days_price' :df_dates[1][coin][1],
                            '14days_price' :df_dates[1][coin][4],
                            '30days_price' :df_dates[1][coin][8]
                            }
        coins_list.append(coins_return_dict)
    elif dates_len >= 17 & dates_len <= 25:
        coin5 = coin5 + 1
        coins_return_dict = {'Coin' : coin, 
                            'launch_date' : df_dates.loc[coin][1].index[0], 
                            'launch_price' : df_dates[0][coin][0],
                            '0days_price' :df_dates[1][coin][0],
                            '4days_price' :df_dates[1][coin][1],
                            '14days_price' :df_dates[1][coin][4],
                            '30days_price' :df_dates[1][coin][8],
                            '60days_price' :df_dates[1][coin][16]
                            }
        coins_list.append(coins_return_dict)
    elif dates_len >= 25:
        coin6 = coin6 + 1
        coins_return_dict = {'Coin' : coin, 
                            'launch_date' : df_dates.loc[coin][1].index[0], 
                            'launch_price' : df_dates[0][coin][0],
                            '0days_price' :df_dates[1][coin][0],
                            '4days_price' :df_dates[1][coin][1],
                            '14days_price' :df_dates[1][coin][4],
                            '30days_price' :df_dates[1][coin][8],
                            '60days_price' :df_dates[1][coin][16]
                            
                            }
        coins_list.append(coins_return_dict)

In [639]:
df_dates[1]['gamium']

Date
2022-03-30 21:00:00         NaN
2022-04-02 21:00:00         NaN
2022-04-06 21:00:00    0.006565
2022-04-10 21:00:00    0.006728
2022-04-14 21:00:00         NaN
Name: Close, dtype: float64

In [573]:
pd.DataFrame(coins_list)

,Coin,launch_date,launch_price,0days_price,4days_price,14days_price
0,01coin,2018-09-14 21:00:00,0.009788,0.009788,0.011866,0.007109
1,0-5x-long-algorand-token,2020-08-18 21:00:00,11007.430000,11007.430000,11086.450000,11086.450000
2,0-5x-long-altcoin-index-token,2020-10-22 21:00:00,7786.400000,7786.400000,7786.400000,7764.670000
3,0-5x-long-ascendex-token-token,2020-11-06 21:00:00,6605.010000,6709.190000,6775.990000,6775.990000
4,0-5x-long-bitcoin-cash-token,2020-08-06 21:00:00,7240.230000,7240.230000,7106.510000,7048.080000
...,...,...,...,...,...,...
13236,thekey,2018-02-14 22:00:00,0.039353,0.039353,0.033518,0.025880
13237,mooncake,2021-08-14 21:00:00,0.100341,0.102276,0.098183,0.140111
13238,wolf-game-wool,2021-11-22 21:00:00,0.176737,0.176737,0.120617,0.062816
13239,misty-inu,2021-10-22 21:00:00,0.001384,0.001602,0.002878,0.000508
13240,mintstarter,2022-03-18 21:00:00,0.009659,0.009659,0.006735,0.005172

In [579]:
print(coin1)
print(coin2)
print(coin3)
print(coin4)

60
245
12936
0

In [587]:
df_dates[1]['gamium'].iloc[[0,1,4]]
#0 lancamento
#1 4 dias
#4 14 dias
#8 1 mes
#24 3 meses
#48 6 meses
#96 1 ano

Date
2022-03-30 21:00:00    0.004766
2022-04-02 21:00:00    0.006807
2022-04-14 21:00:00    0.005791
Name: Close, dtype: float64